apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
  namespace: new-namespace
spec:
  type: LoadBalancer
  loadBalancerIP: 35.224.158.212
  selector:
    app: portfolio
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000

